---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Install Docker Python package
  pip:
    name: docker
    state: present

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add deployment user to Docker group
  user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Docker networks
  docker_network:
    name: "{{ item }}"
    state: present
  loop:
    - frontend
    - backend 