---
- name: Deploy Todo Application
  hosts: all
  become: yes
  vars_files:
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/production.yml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: docker-setup
      tags: ['docker', 'setup']

    - role: todoapp-deploy
      tags: ['app', 'deploy']

  post_tasks:
    - name: Check application health
      uri:
        url: "http://localhost/health"
        return_content: yes
      register: health_check
      failed_when: health_check.status != 200
      tags: ['health']

    - name: Show application status
      debug:
        msg: "Application is running and healthy"
      when: health_check.status == 200
      tags: ['health'] 